version: '2.3'
services:
  db:
    image: mariadb
    command: mysqld --port=3360
    ports:
      - 3360
    network_mode: bridge
    volumes:
      - mariadb:/var/lib/mysql
      - ./backups/create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
      - ./backups:/var/backups
    environment:
      - MYSQL_DATABASE=rf-woocommerce
      - MYSQL_ROOT_PASSWORD=live_usom
      - MYSQL_USER=live_usom
      - MYSQL_PASSWORD=live_usom
      - DNSDOCK_ALIAS=db.woocommerce.docker
    restart: always

  wordpress:
    build:
      context: .
      args:
        - PHPVERSION=5.6-fpm
    working_dir: /var/www/wordpress/wp-content/plugins-test/lendingworks
    environment:
      COMPOSER_HOME: /var/www/wordpress/wp-content/plugins-test/lendingworks/.composer
      SANDBOX_URL: https://retail-sandbox.lendingworks.co.uk/api/v2/
    network_mode: bridge
    volumes:
      - ./wordpress:/var/www/wordpress/
      - ./conf/wp-config.php:/var/www/wordpress/wp-config.php
      - ./lendingworks:/var/www/wordpress/wp-content/plugins/lendingworks
      - ./composer.dist.json:/var/www/wordpress/wp-content/plugins/lendingworks/composer.json
      - .:/var/www/wordpress/wp-content/plugins-test/lendingworks
    depends_on:
      - db
    links:
      - db
    restart: always

  web:
    image: nginx:latest
    ports:
      - 8080:8080
    network_mode: bridge
    links:
      - wordpress
    environment:
      - DNSDOCK_ALIAS=woocommerce.docker
    volumes:
      - ./wordpress:/var/www/wordpress/
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/wp-config.php:/var/www/wordpress/wp-config.php
      - ./lendingworks:/var/www/wordpress/wp-content/plugins/lendingworks
    depends_on:
      - wordpress
    restart: always
volumes:
  mariadb:
